version: '3'
services:
  php-apache:
    build:
      context: .
    ports:
      -  80:80
      -  3306:3306
    volumes:
      - ./www:/var/www/localhost/htdocs
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root